# Workflowの名前
name: java test

# Workflowを動かすトリガー（=Event）を指定。
# 今回はpushをEventに設定
on:
  - push

jobs:
  # build job
  build:
    # Runnerを指定
    runs-on: ubuntu-latest
    # Step
    steps:
      # コードチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      # Java 17をセットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # maven build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./
      # フォーマッター実行
      - name: Run Eclipse Formatter
        run: |
          mvn formatter:format
          mvn formatter:validate
      # フォーマッターによる変更を自動コミット
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Formatted code"
      # Test実行
      - name: Test with Maven
        run: mvn --batch-mode test
        working-directory: ./